# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W8pi_BpZnaZMeIDLivCLTGcDL_ALRXmD
"""

#%pip install streamlit

import streamlit as st
import pickle
import numpy as np

with open("vehicle_insurance.pkl", "rb") as file:
    model = pickle.load(file)

st.title("🚗 Vehicle Insurance Damage Prediction")
st.markdown("Predict whether a customer's vehicle is likely to be damaged based on their details.")

id_input = st.number_input("Customer ID", min_value=0, step=1)
driving_license = st.radio("Driving License", [0, 1], format_func=lambda x: "Yes" if x else "No")
veh_age = st.radio("Vehicle Age", [0, 1, 2], format_func=lambda x: {0: "Old", 1: "1-2 Years", 2: "< 1 Year"}[x])
annual_premium = st.number_input("Annual Premium", min_value=0, step=100)

if st.button("Predict"):
    input_data = np.array([[id_input, driving_license, veh_age, annual_premium]])
    prediction = model.predict(input_data)[0]
    result = "✅ Damage Likely" if prediction == 1 else "❌ No Damage"
    st.success(f"Prediction: {result}")